.TH  1 Dupe
.SH NAME
dupe \- duplicate file finder / remover
.SH SYNOPSIS
.B dupe
.RB [ args ]
.RB [ files / folders ]
.SH DESCRIPTION
dupe is a platform-agnostic duplicate file finder and remover. By
default, it (sanely) requires user input to make a decision regarding
which file to delete and which file to keep.
.SH OPTIONS
.TP
.B \-h
prints information regarding how to find help. It points you here.
.TP
.B \-r
makes dupe work recursively
.SH CHARITY
.TP
If you find this software useful, please consider donating to Meningitis U.K. or your local meningitis charity.
.B http://www.meningitisuk.org
